import { currency, useData } from './data'
import { useState } from 'react'
import { post, put, remove } from '../api'
import { Badge, Button, DataState, Empty, ErrorMessage, Field, Icon, IconButton, Modal, PageHeading, Panel, Table, Tabs } from './shared'
import './menu-editor.css'

function Editor({ title, initial, fields, endpoint, onClose, onSaved, onDelete }) {
  const [form, setForm] = useState(initial)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState(null)
  const submit = async (event) => {
    event.preventDefault(); setBusy(true); setError(null)
    try { await (initial.id ? put(`${endpoint}/${initial.id}`, form) : post(endpoint, form)); onSaved(); onClose() }
    catch (e) { setError(e) } finally { setBusy(false) }
  }
  return <Modal title={title} onClose={() => !busy && onClose()}><form className="a-form" onSubmit={submit}><ErrorMessage error={error} />{fields.map(({ key, label, options, type, ...props }) => <Field key={key} label={label}>{options ? <select value={String(form[key] ?? '')} onChange={(e) => setForm({ ...form, [key]: e.target.value })} {...props}>{options.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select> : type === 'textarea' ? <textarea value={form[key] || ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} {...props} /> : <input type={type || 'text'} value={form[key] ?? ''} onChange={(e) => setForm({ ...form, [key]: e.target.value })} {...props} />}</Field>)}<div className="a-form-footer">{onDelete && <Button type="button" className="a-danger" disabled={busy} onClick={async () => { if (!confirm(`Delete ${initial.name}?`)) return; setBusy(true); try { await onDelete(); onSaved(); onClose() } catch (e) { setError(e) } finally { setBusy(false) } }}>Delete category</Button>}<Button type="button" onClick={onClose} disabled={busy}>Cancel</Button><Button primary disabled={busy}>{busy ? 'Saving…' : 'Save changes'}</Button></div></form></Modal>
}

export function TablesPage() {
  const resource = useData('/restaurant-tables')
  const [editing, setEditing] = useState(null)
  const [qr, setQr] = useState(null)
  const [qrError, setQrError] = useState(false)
  const tables = [...(resource.data?.[0]?.data || [])].sort((a, b) => a.table_number.localeCompare(b.table_number, undefined, { numeric: true }))
  return <><PageHeading eyebrow="Floor plan" title="Tables & QR"><Button icon="plus" onClick={() => setEditing({ table_number: '', capacity: 2, status: 'available' })}>Add table</Button></PageHeading><DataState resource={resource}><div className="a-card-grid a-tables">{tables.map((table) => <article className="a-table-card" key={table.id}><div className="a-card-heading"><div><span className="a-eyebrow">Table</span><h2>{table.table_number.padStart(2, '0')}</h2></div><Badge value={table.status} /></div><p>Seats {table.capacity}</p><div className="a-actions"><Button icon="tables" onClick={() => { setQr(table); setQrError(false) }}>QR</Button><Button icon="edit" onClick={() => setEditing(table)}>Edit</Button></div></article>)}</div>{!tables.length && <Empty>No tables yet. Add a table to generate its ordering QR code.</Empty>}</DataState>{editing && <Editor title={editing.id ? 'Edit table' : 'Add table'} initial={editing} endpoint="/restaurant-tables" fields={[{ key: 'table_number', label: 'Table number', required: true, maxLength: 50 }, { key: 'capacity', label: 'Seats', type: 'number', required: true, min: 1, step: 1 }, { key: 'status', label: 'Status', options: ['available', 'occupied', 'reserved'].map((s) => [s, s]) }]} onSaved={resource.refresh} onClose={() => setEditing(null)} />}{qr && <Modal title={`Table ${qr.table_number} · Ordering QR`} onClose={() => setQr(null)}><div className="a-qr">{qrError ? <ErrorMessage error={{ message: 'QR code could not be loaded. Close and try again.' }} /> : <img src={`${(import.meta.env.VITE_API_BASE_URL || '/api').replace(/\/$/, '')}/restaurant-tables/${qr.id}/qr`} alt={`Scan to order at table ${qr.table_number}`} onError={() => setQrError(true)} />}<p>Scan this code to open the menu for this table.</p></div></Modal>}</>
}

export function CategoriesPage() {
  const resource = useData('/categories', '/menu-items')
  const [editing, setEditing] = useState(null)
  const [error, setError] = useState(null)
  const [busy, setBusy] = useState(false)
  const categories = resource.data?.[0]?.data || []
  const items = resource.data?.[1]?.data || []
  const toggle = async (category) => { setBusy(true); setError(null); try { await put(`/categories/${category.id}`, { is_active: !category.is_active }); resource.refresh() } catch (e) { setError(e) } finally { setBusy(false) } }
  return <><PageHeading eyebrow="Menu structure" title="Categories"><Button icon="plus" onClick={() => setEditing({ name: '', description: '' })}>Add category</Button></PageHeading><ErrorMessage error={error} /><DataState resource={resource}><Panel className="a-table-panel"><Table headings={['Category', 'Items', 'Status', 'Actions']} rows={categories.map((category) => <tr key={category.id}><td><strong>{category.name}</strong><small>{category.description}</small></td><td>{items.filter((item) => item.category_id === category.id).length} items</td><td><Badge value={category.is_active ? 'active' : 'inactive'} /></td><td><div className="a-actions"><IconButton icon="edit" label={`Edit ${category.name}`} onClick={() => setEditing(category)} /><IconButton icon="power" label={`${category.is_active ? 'Deactivate' : 'Activate'} ${category.name}`} disabled={busy} onClick={() => toggle(category)} /></div></td></tr>)} /></Panel></DataState>{editing && <Editor title={editing.id ? 'Edit category' : 'Add category'} initial={editing} fields={[{ key: 'name', label: 'Category name', required: true, maxLength: 100 }, { key: 'description', label: 'Description', type: 'textarea' }]} endpoint="/categories" onDelete={editing.id ? () => remove(`/categories/${editing.id}`) : null} onSaved={resource.refresh} onClose={() => setEditing(null)} />}</>
}

export function LegacyMenuPage() {
  const resource = useData('/categories', '/menu-items', '/inventories')
  const [category, setCategory] = useState('all')
  const [editing, setEditing] = useState(null)
  const [error, setError] = useState(null)
  const [busy, setBusy] = useState(false)
  const categories = resource.data?.[0]?.data || []
  const items = resource.data?.[1]?.data || []
  const inventories = resource.data?.[2]?.data || []
  const toggle = async (item) => { setBusy(true); setError(null); try { await put(`/menu-items/${item.id}`, { is_available: !item.is_available }); resource.refresh() } catch (e) { setError(e) } finally { setBusy(false) } }
  const visible = items.filter((item) => category === 'all' || String(item.category_id) === category)
  return <><PageHeading eyebrow="Kitchen catalog" title="Menu items"><Button icon="plus" onClick={() => setEditing({ name: '', description: '', price: '', category_id: '' })}>Add menu item</Button></PageHeading><ErrorMessage error={error} /><DataState resource={resource}><Tabs values={[["all", 'All'], ...categories.map((c) => [String(c.id), c.name])]} value={category} onChange={setCategory} /><div className="a-card-grid a-menu-grid">{visible.map((item) => { const inventory = inventories.find((i) => i.menu_item.id === item.id); return <article className="a-menu-card" key={item.id}><div className="a-item-icon"><Icon name="menu" size={30} /></div><div className="a-card-heading"><h3>{item.name}</h3><strong>{currency(item.price)}</strong></div><small>{item.category?.name}</small><p>{item.description || 'No description added.'}</p><div className="a-badges"><Badge value={item.is_available ? 'available' : 'unavailable'} />{inventory && <Badge value={inventory.quantity === 0 ? 'out-of-stock' : inventory.is_low_stock ? 'low-stock' : 'in-stock'}>{inventory.quantity === 0 ? 'Out of stock' : inventory.is_low_stock ? 'Low stock' : `${inventory.quantity} in stock`}</Badge>}</div><div className="a-actions"><Button icon="edit" onClick={() => setEditing({ id: item.id, name: item.name, category_id: item.category_id, description: item.description || '', price: item.price })}>Edit</Button><Button icon="power" disabled={busy} onClick={() => toggle(item)}>Mark {item.is_available ? 'unavailable' : 'available'}</Button></div></article> })}</div>{!visible.length && <Empty>No menu items in this category.</Empty>}</DataState>{editing && <Editor title={editing.id ? 'Edit menu item' : 'Add menu item'} initial={editing} endpoint="/menu-items" fields={[{ key: 'name', label: 'Name', required: true, maxLength: 150 }, { key: 'category_id', label: 'Category', required: true, options: [['', 'Choose category'], ...categories.map((c) => [c.id, c.name])] }, { key: 'price', label: 'Price (₱)', type: 'number', required: true, min: 0, step: '0.01' }, { key: 'description', label: 'Description', type: 'textarea' }]} onSaved={resource.refresh} onClose={() => setEditing(null)} />}</>
}

export function MenuPage() {
  const resource = useData('/categories', '/menu-items', '/inventories')
  const [category, setCategory] = useState('all')
  const [editing, setEditing] = useState(null)
  const [error, setError] = useState(null)
  const [busy, setBusy] = useState(false)
  const categories = resource.data?.[0]?.data || []
  const items = resource.data?.[1]?.data || []
  const inventories = resource.data?.[2]?.data || []
  const visible = items.filter((item) => category === 'all' || String(item.category_id) === category)
  const toggle = async (item) => { setBusy(true); setError(null); try { await put(`/menu-items/${item.id}`, { is_available: !item.is_available }); resource.refresh() } catch (requestError) { setError(requestError) } finally { setBusy(false) } }
  const edit = (item) => { const inventory = inventories.find((record) => record.menu_item.id === item.id); setEditing({ id: item.id, name: item.name, category_id: item.category_id, description: item.description || '', price: item.price, inventory }) }

  return <><PageHeading eyebrow="Kitchen catalog" title="Menu items"><Button icon="plus" onClick={() => setEditing({ name: '', description: '', price: '', category_id: '' })}>Add menu item</Button></PageHeading><ErrorMessage error={error} /><DataState resource={resource}><Tabs values={[["all", 'All'], ...categories.map((item) => [String(item.id), item.name])]} value={category} onChange={setCategory} /><div className="a-card-grid a-menu-grid">{visible.map((item) => { const inventory = inventories.find((record) => record.menu_item.id === item.id); return <article className="a-menu-card" key={item.id}><div className="a-item-icon"><Icon name="menu" size={30} /></div><div className="a-card-heading"><h3>{item.name}</h3><strong>{currency(item.price)}</strong></div><small>{item.category?.name}</small><p>{item.description || 'No description added.'}</p><div className="a-badges"><Badge value={item.is_available ? 'available' : 'unavailable'} />{inventory && <Badge value={inventory.quantity === 0 ? 'out-of-stock' : inventory.is_low_stock ? 'low-stock' : 'in-stock'}>{inventory.quantity === 0 ? 'Out of stock' : inventory.is_low_stock ? 'Low stock' : `${inventory.quantity} in stock`}</Badge>}</div><div className="a-actions"><Button icon="edit" onClick={() => edit(item)}>Edit</Button><Button icon="power" disabled={busy} onClick={() => toggle(item)}>Mark {item.is_available ? 'unavailable' : 'available'}</Button></div></article> })}</div>{!visible.length && <Empty>No menu items in this category.</Empty>}</DataState>{editing && <MenuItemEditor initial={editing} categories={categories} onClose={() => setEditing(null)} onSaved={resource.refresh} />}</>
}

function MenuItemEditor({ initial, categories, onClose, onSaved }) {
  const [form, setForm] = useState(initial)
  const [stock, setStock] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState(null)
  const update = (key, value) => setForm({ ...form, [key]: value })
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(null); try { const payload = { name: form.name, category_id: form.category_id, price: form.price, description: form.description }; await (form.id ? put(`/menu-items/${form.id}`, payload) : post('/menu-items', payload)); onSaved(); onClose() } catch (requestError) { setError(requestError) } finally { setBusy(false) } }
  const addStock = async () => { if (!form.inventory || !stock) return; setBusy(true); setError(null); try { await post(`/inventories/${form.inventory.id}/restock`, { quantity: Number(stock), reason: 'Added from menu item editor' }); onSaved(); onClose() } catch (requestError) { setError(requestError) } finally { setBusy(false) } }
  const deleteItem = async () => { if (!confirm(`Delete ${form.name}? This cannot be undone.`)) return; setBusy(true); setError(null); try { await remove(`/menu-items/${form.id}`); onSaved(); onClose() } catch (requestError) { setError(requestError) } finally { setBusy(false) } }

  return <Modal title={form.id ? `Edit menu item · ${form.name}` : 'Add menu item'} onClose={() => !busy && onClose()}><form className="a-form" onSubmit={save}><ErrorMessage error={error} /><Field label="Name" required maxLength={150} value={form.name} onChange={(event) => update('name', event.target.value)} /><Field label="Category"><select required value={form.category_id} onChange={(event) => update('category_id', event.target.value)}><option value="">Choose category</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></Field><Field label="Price (₱)" type="number" required min={0} step="0.01" value={form.price} onChange={(event) => update('price', event.target.value)} /><Field label="Description"><textarea value={form.description} onChange={(event) => update('description', event.target.value)} /></Field>{form.inventory && <section className="menu-stock-editor"><strong>Stock: {form.inventory.quantity} units</strong><div><Field label="Add stock" type="number" min={1} step={1} placeholder="Quantity" value={stock} onChange={(event) => setStock(event.target.value)} /><Button type="button" icon="plus" disabled={busy || !stock} onClick={addStock}>Add stock</Button></div></section>}<div className="a-form-footer">{form.id && <Button type="button" className="a-danger" disabled={busy} onClick={deleteItem}>Delete item</Button>}<Button type="button" disabled={busy} onClick={onClose}>Cancel</Button><Button primary disabled={busy}>{busy ? 'Saving…' : 'Save changes'}</Button></div></form></Modal>
}

export function UsersPage({ currentUser }) {
  const resource = useData('/admin/users')
  const [editing, setEditing] = useState(null)
  const [passwordUser, setPasswordUser] = useState(null)
  const [error, setError] = useState(null)
  const [busy, setBusy] = useState(false)
  const [profileView, setProfileView] = useState('profile')
  const [viewedCashier, setViewedCashier] = useState(null)
  const mutate = async (fn) => { setBusy(true); setError(null); try { await fn(); resource.refresh() } catch (e) { setError(e) } finally { setBusy(false) } }
  const users = resource.data?.[0]?.data || []
  const visibleUsers = users.filter((user) => profileView === 'profile' ? user.role === 'admin' : user.role === 'cashier')
  if (profileView === 'profile') return <AdminProfileView user={currentUser} onBack={() => setProfileView('accounts')} />
  if (viewedCashier) return <CashierProfileView user={viewedCashier} onBack={() => setViewedCashier(null)} onSaved={resource.refresh} />
  return <><PageHeading eyebrow="User management" title="Users" description="Manage the admin account and cashier accounts." /><div className="profile-tabs"><Tabs values={[["profile", "Admin profile"], ["accounts", "Cashier accounts"]]} value={profileView} onChange={setProfileView} /></div><ErrorMessage error={error} /><DataState resource={resource}><Panel title="Cashier accounts" action={<Button primary icon="plus" onClick={() => setEditing({ name: '', email: '', role: 'cashier', password: '', password_confirmation: '' })}>Create cashier account</Button>} className="a-table-panel cashier-accounts-panel"><Table headings={['Cashier', 'Username', 'Date created', 'Status', 'Actions']} rows={visibleUsers.map((user) => <tr key={user.id}><td><button className="cashier-name cashier-profile-link" title={`Open ${user.name}'s profile`} onClick={() => setViewedCashier(user)}><span className="cashier-avatar">{user.name.split(/\s+/).map((part) => part[0]).slice(0, 2).join('').toUpperCase()}</span><strong>{user.name}</strong></button></td><td>{user.email}</td><td>{user.created_at ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(user.created_at)) : '—'}</td><td><Badge value={user.is_active ? 'active' : 'inactive'}>{user.is_active ? '● Active' : '● Deactivated'}</Badge></td><td><div className="cashier-actions"><Button className={`cashier-status-toggle ${user.is_active ? 'is-active' : ''}`} aria-label={`${user.is_active ? 'Deactivate' : 'Activate'} ${user.name}`} title={`${user.is_active ? 'Deactivate' : 'Activate'} ${user.name}`} disabled={busy} onClick={() => mutate(() => post(`/admin/users/${user.id}/${user.is_active ? 'deactivate' : 'activate'}`, {}))} /></div></td></tr>)} empty="No cashier accounts yet. Create one to give a cashier access." /></Panel></DataState>{editing && <Editor title={editing.id ? 'Edit cashier account' : 'Create cashier account'} initial={editing} endpoint="/admin/users" onSaved={resource.refresh} onClose={() => setEditing(null)} fields={[{ key: 'name', label: 'Name', required: true }, { key: 'email', label: 'Email', type: 'email', required: true }, ...(!editing.id ? [{ key: 'password', label: 'Password', type: 'password', minLength: 8, required: true, autoComplete: 'new-password' }, { key: 'password_confirmation', label: 'Confirm password', type: 'password', minLength: 8, required: true, autoComplete: 'new-password' }] : [])]} />}{passwordUser && <PasswordDialog user={passwordUser} onClose={() => setPasswordUser(null)} />}</>
}

function CashierProfileView({ user, onBack, onSaved }) {
  const [view, setView] = useState('profile')
  const createdAt = user.created_at ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(user.created_at)) : '—'
  return <><PageHeading eyebrow="Cashier account" title="Profile" description="View and manage this cashier account." /><div className="profile-tabs profile-tabs-secondary"><Tabs values={[["profile", 'Profile'], ["edit", 'Edit profile']]} value={view} onChange={setView} /></div>{view === 'profile' ? <Panel className="profile-summary cashier-profile-summary"><div className="a-avatar profile-avatar">{user.name?.[0]?.toUpperCase()}</div><div className="profile-facts"><span className="a-eyebrow">Full name</span><strong>{user.name}</strong><span className="a-eyebrow">Role</span><strong>Cashier</strong><span className="a-eyebrow">Date created</span><strong>{createdAt}</strong></div><div className="profile-facts"><span className="a-eyebrow">Username / Email</span><strong>{user.email}</strong><span className="a-eyebrow">Account status</span><strong className="profile-status">{user.is_active ? '● Active' : '● Deactivated'}</strong></div><div className="a-actions"><Button primary onClick={() => setView('edit')}>Edit profile</Button><Button className="cashier-profile-back" onClick={onBack}>Back to cashier accounts</Button></div></Panel> : <CashierAccountEditor user={user} onSaved={onSaved} onCancel={() => setView('profile')} />}</>
}

function CashierAccountEditor({ user, onSaved, onCancel }) {
  const [details, setDetails] = useState({ name: user.name, email: user.email })
  const [password, setPassword] = useState({ current_password: '', password: '', password_confirmation: '' })
  const [detailsError, setDetailsError] = useState(null)
  const [passwordError, setPasswordError] = useState(null)
  const [savingDetails, setSavingDetails] = useState(false)
  const [savingPassword, setSavingPassword] = useState(false)
  const saveDetails = async (event) => { event.preventDefault(); setSavingDetails(true); setDetailsError(null); try { await put(`/admin/users/${user.id}`, details); onSaved() } catch (error) { setDetailsError(error) } finally { setSavingDetails(false) } }
  const savePassword = async (event) => { event.preventDefault(); setSavingPassword(true); setPasswordError(null); try { await post(`/admin/users/${user.id}/password`, password); setPassword({ current_password: '', password: '', password_confirmation: '' }) } catch (error) { setPasswordError(error) } finally { setSavingPassword(false) } }
  return <div className="profile-editor"><form className="a-panel profile-edit-card" onSubmit={saveDetails}><ErrorMessage error={detailsError} /><div className="profile-photo"><div className="profile-photo-placeholder">↥</div><div><span className="a-eyebrow">Profile picture</span><label className="profile-upload">Upload new photo<input type="file" accept="image/*" aria-label="Upload a profile photo" /></label></div></div><div className="profile-edit-fields"><Field label="Full name" required value={details.name} onChange={(event) => setDetails({ ...details, name: event.target.value })} /><Field label="Email / Username" type="email" required value={details.email} onChange={(event) => setDetails({ ...details, email: event.target.value })} /></div><div className="a-actions"><Button primary disabled={savingDetails}>{savingDetails ? 'Saving…' : 'Save changes'}</Button><Button type="button" onClick={onCancel}>Cancel</Button></div></form><form className="a-panel profile-password-card" onSubmit={savePassword}><ErrorMessage error={passwordError} /><h2>Change password</h2><p className="a-muted">Set a new password for this cashier account.</p><div className="profile-password-fields"><Field label="Current password" type="password" autoComplete="off" value={password.current_password} onChange={(event) => setPassword({ ...password, current_password: event.target.value })} /><Field label="New password" type="password" autoComplete="new-password" minLength={8} required value={password.password} onChange={(event) => setPassword({ ...password, password: event.target.value })} /><small>Use at least 8 characters, including a number.</small><Field label="Confirm new password" type="password" autoComplete="new-password" minLength={8} required value={password.password_confirmation} onChange={(event) => setPassword({ ...password, password_confirmation: event.target.value })} /></div><div className="a-actions"><Button primary disabled={savingPassword}>{savingPassword ? 'Updating…' : 'Update password'}</Button><Button type="button" onClick={() => setPassword({ current_password: '', password: '', password_confirmation: '' })}>Cancel</Button></div></form></div>
}

function AdminProfileView({ user, onBack }) {
  const [view, setView] = useState('profile')
  const createdAt = user.created_at ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(user.created_at)) : '—'
  return <><PageHeading eyebrow="User management" title="Users" description="Manage the admin account and cashier accounts." /><div className="profile-tabs"><Tabs values={[["profile", 'Admin profile'], ["accounts", 'Cashier accounts']]} value="profile" onChange={onBack} /></div><div className="profile-tabs profile-tabs-secondary"><Tabs values={[["profile", 'Profile'], ["edit", 'Edit profile']]} value={view} onChange={setView} /></div>{view === 'profile' ? <Panel className="profile-summary"><div className="a-avatar profile-avatar">{user.name?.[0]?.toUpperCase()}</div><div className="profile-facts"><span className="a-eyebrow">Full name</span><strong>{user.name}</strong><span className="a-eyebrow">Role</span><strong>Administrator</strong><span className="a-eyebrow">Date created</span><strong>{createdAt}</strong></div><div className="profile-facts"><span className="a-eyebrow">Username / Email</span><strong>{user.email}</strong><span className="a-eyebrow">Account status</span><strong className="profile-status">● Active</strong></div><div className="a-actions"><Button primary onClick={() => setView('edit')}>Edit profile</Button></div></Panel> : <ProfileEditor user={user} onCancel={() => setView('profile')} />}</>
}

function ProfileEditor({ user, onCancel }) {
  const [profile, setProfile] = useState({ name: user.name, email: user.email })
  const [password, setPassword] = useState({ current_password: '', password: '', password_confirmation: '' })
  const [profileError, setProfileError] = useState(null)
  const [passwordError, setPasswordError] = useState(null)
  const [savingProfile, setSavingProfile] = useState(false)
  const [savingPassword, setSavingPassword] = useState(false)
  const setProfileValue = (key, value) => setProfile({ ...profile, [key]: value })
  const setPasswordValue = (key, value) => setPassword({ ...password, [key]: value })
  const saveProfile = async (event) => { event.preventDefault(); setSavingProfile(true); setProfileError(null); try { await put('/profile', { name: profile.name, email: profile.email }) } catch (error) { setProfileError(error) } finally { setSavingProfile(false) } }
  const savePassword = async (event) => { event.preventDefault(); setSavingPassword(true); setPasswordError(null); try { await post('/profile/password', password); setPassword({ current_password: '', password: '', password_confirmation: '' }) } catch (error) { setPasswordError(error) } finally { setSavingPassword(false) } }
  return <div className="profile-editor"><form className="a-panel profile-edit-card" onSubmit={saveProfile}><ErrorMessage error={profileError} /><div className="profile-photo"><div className="profile-photo-placeholder">↥</div><div><span className="a-eyebrow">Profile picture</span><label className="profile-upload">Upload new photo<input type="file" accept="image/*" aria-label="Upload a profile photo" /></label></div></div><div className="profile-edit-fields"><Field label="Full name" required value={profile.name} onChange={(event) => setProfileValue('name', event.target.value)} /><Field label="Email / Username" type="email" required value={profile.email} onChange={(event) => setProfileValue('email', event.target.value)} /></div><div className="a-actions"><Button primary disabled={savingProfile}>{savingProfile ? 'Saving…' : 'Save changes'}</Button><Button type="button" disabled={savingProfile} onClick={onCancel}>Cancel</Button></div></form><form className="a-panel profile-password-card" onSubmit={savePassword}><ErrorMessage error={passwordError} /><h2>Change password</h2><p className="a-muted">Leave these blank to keep your current password.</p><div className="profile-password-fields"><Field label="Current password" type="password" autoComplete="current-password" required value={password.current_password} onChange={(event) => setPasswordValue('current_password', event.target.value)} /><Field label="New password" type="password" autoComplete="new-password" minLength={8} required value={password.password} onChange={(event) => setPasswordValue('password', event.target.value)} /><small>Use at least 8 characters, including a number.</small><Field label="Confirm new password" type="password" autoComplete="new-password" minLength={8} required value={password.password_confirmation} onChange={(event) => setPasswordValue('password_confirmation', event.target.value)} /></div><div className="a-actions"><Button primary disabled={savingPassword}>{savingPassword ? 'Updating…' : 'Update password'}</Button><Button type="button" disabled={savingPassword} onClick={() => setPassword({ current_password: '', password: '', password_confirmation: '' })}>Cancel</Button></div></form></div>
}

function PasswordDialog({ user, onClose }) {
  const [password, setPassword] = useState('')
  const [confirmation, setConfirmation] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmation, setShowConfirmation] = useState(false)
  const [error, setError] = useState(null)
  const [busy, setBusy] = useState(false)
  return <Modal title={`Set password · ${user.name}`} onClose={() => !busy && onClose()}><form className="a-form" onSubmit={async (e) => { e.preventDefault(); setBusy(true); setError(null); try { await post(`/admin/users/${user.id}/password`, { password, password_confirmation: confirmation }); onClose() } catch (e) { setError(e) } finally { setBusy(false) } }}><ErrorMessage error={error} /><Field label="New password"><span className="password-field"><input type={showPassword ? 'text' : 'password'} autoComplete="new-password" minLength={8} required value={password} onChange={(e) => setPassword(e.target.value)} /><button type="button" className="password-toggle" aria-pressed={showPassword} aria-label={showPassword ? 'Hide password' : 'Show password'} onClick={() => setShowPassword((visible) => !visible)}>{showPassword ? 'Hide' : 'Show'}</button></span></Field><Field label="Confirm password"><span className="password-field"><input type={showConfirmation ? 'text' : 'password'} autoComplete="new-password" minLength={8} required value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /><button type="button" className="password-toggle" aria-pressed={showConfirmation} aria-label={showConfirmation ? 'Hide confirmed password' : 'Show confirmed password'} onClick={() => setShowConfirmation((visible) => !visible)}>{showConfirmation ? 'Hide' : 'Show'}</button></span></Field><div className="a-form-footer"><Button type="button" disabled={busy} onClick={onClose}>Cancel</Button><Button primary disabled={busy}>{busy ? 'Saving…' : 'Set password'}</Button></div></form></Modal>
}
